title: CEREA DA-ML
description: Website of the CEREA DA-ML team
theme: just-the-docs

url: https://cerea-daml.github.io

aux_links:
  CEREA: https://www.cerea-lab.fr
  CEREA DA-ML on GitHub: https://github.com/cerea-daml
